spring.datasource.url=jdbc:postgresql://localhost:5432/shortener
spring.datasource.username=shortener
spring.datasource.password=shortener
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

spring.cache.type=redis
spring.cache.redis.time-to-live=10m
spring.data.redis.host=localhost
spring.data.redis.port=6379